### PR TITLE
 CMake

### PR DESCRIPTION
**Pull request by jmc-88**
Not perfect, but it's a start.

Disclaimer: since this hasn't gone through Travis yet, there's a chance it'll fail the build (especially if the `cmake_minimum_required` constraint fails due to the VM having an older `cmake` package). I'll amend as needed later.

### CODE REVIEW

**Comment by jmc-88** [comment]
And indeed there's a small issue there: `generateDocumentationAndDeploy.sh` invokes `doxygen` which fails (but, amazingly, this doesn't fail the build as the exit code for the script is still `0` -- that would need fixing as well).

**Comment by jmc-88** [comment]
Actually, never mind: I see that part was already broken (e.g. compare with https://travis-ci.org/italia/cie-nis-cpp-sdk/builds/393293180, which shows the same `error: configuration file /home/travis/build/italia/cie-nis-cpp-sdk/Doxyfile.Travis not found!`).

In fact, the `DOXYFILE` variable points to the wrong location: https://github.com/italia/cie-nis-cpp-sdk/blob/bcc03896ac81e788fcf0e5da7a1d319150242866/.travis.yml#L12
After all, I'm not sure the CI environment should push documentation in the first place (?). I'll leave it as is.

**Comment by sfaragnaus** [comment]
The build runs just fine, I'm not entirely sure why you chose to link all single source file into a static lib. Can you please explain the reasoning behind that?
Many thanks

**Comment by jmc-88** [comment]
What I was trying to achieve was making the dependencies and relationships between those compilation units explicit -- i.e. I was trying something similar to Bazel's [`cc_library`](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library).

Problem is, aside from the slight abuse of [`add_library`](https://cmake.org/cmake/help/v3.12/command/add_library.html), that hardcoding everything as `STATIC` means the user can't decide if they want static or dynamic linkage. I'm going to amend that by bringing the targets back into a single `add_library` invocation and removing the explicit `STATIC` so that the user can control the build through the [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.12/variable/BUILD_SHARED_LIBS.html) option.

**Comment by jmc-88** [comment]
Sorry. Did not mean to close.

**Comment by sfaragnaus** [comment]
Much cleaner now. Can I kindly ask you to further improve the CMakeFile adding source dependencies  in each subdirectory under src/, instead of globbing all of them inside the roto CMakeFIle? E.g.  src/util should have its own CMakeFile that adds the sources under that directory to the common 'cienis' target library. This way any directory refactoring will be much simpler. Also, adding some install rules would be top-notch. 
+1 for not having used GLOB_RECURSE. 
Thanks

**Comment by alexrj** [comment]
Thank you @jmc-88 for working on that!

**Comment by jmc-88** [comment]
Whoops. I had an `install()` rule for the actual library, but I inadvertently removed that in ff0982270f7c07581acd64399fb1a5b5996dfa83. Let me add it back...
Other installation targets for documentation artifacts and for example binaries are already there.

To make this all complete, one might want to export a FindCieNis.cmake or similar (and/or a `pkg-config` module). That might be left to a later stage though.

**Pull request merged**
